### ISSUE TITLE
Plugin hangs when opening

### ISSUE THREAD

**Issue by joshid** [it4biz/pentaho-performance-monitoring#10]
I've installed Pentaho Performance Monitoring on Pentaho 5.0.1 CE server (Windows 2012 Server).
Installation runs ok and registration seems to be correct but when I start the plugin (after BAServer restart) and refresh data it hangs on loading screen.

**Comment by caiomsouza** [comment]
Hi Jose,

Try it on a linux server or a mac and it will work.

It does not work with Windows. We still have a problem with Windows Servers.

See it:
https://github.com/it4biz/pentaho-performance-monitoring/issues/3

Feel free to help us with this problem with Windows.

We are in Madrid, Spain and São Paulo, Brasil feel free to contact us if you have problem in a Linux or Mac Server.

Un saludo,

Caio
