### ISSUE TITLE
Add support for Windows

### ISSUE THREAD

**Issue by fernandommota** [it4biz/pentaho-performance-monitoring#3]
Endpoint: _jobCopyAndClearLogs
Step: Clear log Windows
Error: The path not working and the file is blocked by OS

**Comment by caiomsouza** [comment]
Fernando,

Testei aqui no Windows e funcionou. Isso deve resolver o problema.

type nome_arquivo_com_conteudo_vazio.log catalina.out 

type empty-catalina.out > catalina.out 

Apenas precisa criar um arquivo chamado empty-catalina.out com conteúdo vazio.

Isso deve migrar o conteúdo do arquivo vazio para o catalina.out 

Acredito que o Windows não vai bloquear isso, pelo menos aqui deu certo.

**Comment by fernandommota** [comment]
A solução funciona sim, mas apenas se o biserver estiver off, portanto sem resolução ainda.

**Comment by caiomsouza** [comment]
Devido a todos nossos projetos utilizarem servidores Linux e não termos uma solução até o momento para conseguir fazer funcionar no Windows até o momento esse issue será fechado.

Ele somente será aberto para novas tentativas caso seja patrocinado por algum cliente, caso contrário o plug-in será exclusivo para ambientes Unix (Linux e Mac).
